<?php

/*
 * Plugin Name: Facebook Social Reader
 * Plugin URI: http://personalliberty.com
 * Description: Social Reader for Personal Liberty Media Group.
 * Author: Spencer Cameron
 * Author URI: http://personalliberty.com
 * Version: 1.0
 * License: GPL2
 */

if( ! class_exists( 'FB_Social_Reader' ) ) :

	class FB_Social_Reader {
		
		var $plugin_page_name = 'fb-social-reader';

		var $settings = array(
								'fb_app_id' => 0,
								'fb_app_namespace' => '',
								'fb_app_object' => '',
								'fb_app_delay' => 0 );

		function __construct() {
			add_action( 'wp_head', array( $this, 'add_meta_tags' ) );

			/*
		   	 * Add our admin menu.
			 */
			add_action( 'admin_menu' , array( $this, 'create_settings_menu' ) );

			add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_scripts' ) );

			//add_action( 'the_content', array( $this, 'display_social_reader' ) );

			$this->get_saved_settings();
		}

		function enqueue_scripts() {
			wp_enqueue_script( 'jquery' );
			wp_enqueue_script( 'social-reader-javascript', plugins_url( '/js/social-reader.js', __FILE__ ) );
			wp_enqueue_style( 'social-reader-css', plugins_url( '/css/style.css', __FILE__ ) );
		}

		function add_meta_tags() {
			if( ! is_single() )
				return; ?>

			<meta property="fb:app_id" content="<?php echo esc_attr( $this->settings[ 'fb_app_id' ] ); ?>" />
			<meta property="og:type" content="<?php echo esc_attr( $this->settings[ 'fb_app_namespace' ] ); ?>:article" />
			<meta property="og:title" content="<?php the_title(); ?>" />
			<meta property="og:image" content="<?php echo pl_get_image_url( get_the_ID() ); ?>" />
			<meta property="og:description" content="<?php the_excerpt(); ?>" />
			<meta property="og:url" content="<?php the_permalink(); ?>"><?php
		}

		function get_saved_settings() {
			$this->settings = get_option( $this->plugin_page_name . '-settings' );
		}

		function create_settings_menu() {
			add_options_page( 'Social Reader Settings', 'Social Reader', 'manage_options', $this->plugin_page_name, array( $this, 'create_settings_page' ) );
		}

		function create_settings_page() {
			if(  ! empty( $_POST ) )
				$this->process_form_input();

			$this->generate_settings_form();
		}

		function process_form_input() {
		
			// Make sure there's no monkey-business going on.
			check_admin_referer( $this->plugin_page_name );

			$this->settings[ 'fb_app_id' ] = isset( $_POST[ 'fb_app_id' ] ) ? absint( $_POST[ 'fb_app_id' ] ) : 0;
			$this->settings[ 'fb_app_namespace' ] = isset( $_POST[ 'fb_app_namespace' ] ) ? sanitize_text_field( $_POST[ 'fb_app_namespace' ] ) : '';
			$this->settings[ 'fb_app_object' ] = isset( $_POST[ 'fb_app_object' ] ) ? sanitize_text_field( $_POST[ 'fb_app_object' ] ) : '';
			$this->settings[ 'fb_app_delay' ] = isset( $_POST[ 'fb_app_delay' ] ) ? sanitize_text_field( $_POST[ 'fb_app_delay' ] ) : '';

			return update_option( $this->plugin_page_name . '-settings', $this->settings );
		}

		function generate_settings_form() { ?>
			<div>
				<p>Social Reader Settings</p>
				<form method="post" action="<?php menu_page_url( $this->plugin_page_name ); ?>" >

					<span style="font-size: 14px;">Facebook App ID:</span>
					<input 
						type="text"
						style="width: 200px; display: block; margin: 0 0 20px 0;"
						name="fb_app_id" 
						value="<?php echo esc_attr( $this->settings[ 'fb_app_id' ] ); ?>" />

					<span style="font-size: 14px;">App Namespace:</span>
					<input 
						type="text"
						style="width: 200px; display: block; margin: 0 0 20px 0;"
						name="fb_app_namespace" 
						value="<?php echo esc_attr( $this->settings[ 'fb_app_namespace' ] ); ?>" />

					<span style="font-size: 14px;">Object to Read:</span>
					<input 
						type="text"
						style="width: 200px; display: block; margin: 0 0 20px 0;"
						name="fb_app_object" 
						value="<?php echo esc_attr( $this->settings[ 'fb_app_object' ] ); ?>" />
					<span style="font-size: 14px;">Time to wait before the post is considered read:</span>
					<input 
						type="text"
						style="width: 200px; display: block; margin: 0 0 20px 0;"
						name="fb_app_delay" 
						value="<?php echo esc_attr( $this->settings[ 'fb_app_delay' ] ); ?>" />

					<input 
						type="checkbox"
						style="height: 20px; display: inline;"
						name="override"
						value="" />
					<label style="height: 20px;" for="override">Override open graph tags generated by Jetpack?</label>
					<input style="display: block; margin: 20px 0;" type="submit" value="Update Settings" />
					<?php wp_nonce_field( $this->plugin_page_name ); ?>
				</form>
			</div><?php
		}
	
		function display_social_reader( $content ) {
			$content = '<div id="social-reader">social reader</div>' . $content;			

			return $content;
		}

	}

	new FB_Social_Reader;

endif;
?>
